name: atehere

networks:
  backend_net:

volumes:
  atehere_pg_data:

services:
  app:
    depends_on:
      - db
    mem_limit: 6g
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        ARG CGO_ENABLED: 0
        ARG GO_VERSION: 1.23.2
    command: ["atehere", "-c", "/etc/atehere/application.json"]
    develop:
      watch:
        - action: rebuild
          path: ../
          target: /app
          ignore:
            - development/*
    env_file: ".env.dev"
    ports:
      - 8080:8080
    networks:
      - backend_net
    volumes:
      - ./config:/etc/atehere
      - ./logs:/var/lib/atehere/logs

  db:
    image: postgres:16-bookworm
    env_file: ".env.dev"
    ports:
      - 5432:5432
    networks:
      - backend_net
    volumes:
      - atehere_pg_data:/var/lib/postgresql/data
    restart: always
