// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: customer.sql

package dal

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getCustomer = `-- name: GetCustomer :one
SELECT id, full_name, gender, birth_date, created_at, updated_at, deleted_at FROM customers
WHERE id=$1
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const saveCustomer = `-- name: SaveCustomer :exec
INSERT INTO customers (
    id, full_name, gender, birth_date, created_at, updated_at, deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) ON CONFLICT (id) DO UPDATE SET full_name = $2,gender = $3 ,birth_date = $4, updated_at = NOW()
`

type SaveCustomerParams struct {
	ID        uuid.UUID
	FullName  string
	Gender    string
	BirthDate sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

func (q *Queries) SaveCustomer(ctx context.Context, arg SaveCustomerParams) error {
	_, err := q.db.ExecContext(ctx, saveCustomer,
		arg.ID,
		arg.FullName,
		arg.Gender,
		arg.BirthDate,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
