// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dal

import (
	"database/sql"
)

type Customer struct {
	ID        string
	FullName  string
	BirthDate sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
