// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: restaurant.sql

package dal

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getRestaurant = `-- name: GetRestaurant :one
SELECT id, owner_id, name, foundation_year, phone_number, opening_time, closing_time, working_days, created_at, updated_at, deleted_at FROM restaurants
WHERE id=$1
`

func (q *Queries) GetRestaurant(ctx context.Context, id uuid.UUID) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getRestaurant, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.FoundationYear,
		&i.PhoneNumber,
		&i.OpeningTime,
		&i.ClosingTime,
		pq.Array(&i.WorkingDays),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRestaurantOwner = `-- name: GetRestaurantOwner :one
SELECT m.id, m.full_name, m.phone_number, m.created_at, m.updated_at, m.deleted_at FROM managers m
INNER JOIN restaurants r on m.id=r.owner_id
WHERE m.id=$1
`

func (q *Queries) GetRestaurantOwner(ctx context.Context, id uuid.UUID) (Manager, error) {
	row := q.db.QueryRowContext(ctx, getRestaurantOwner, id)
	var i Manager
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const saveRestaurant = `-- name: SaveRestaurant :exec
INSERT INTO restaurants (
    id, 
    owner_id, 
    name, 
    foundation_year, 
    phone_number, 
    opening_time, 
    closing_time,
    working_days,
    created_at,
    updated_at,
    deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) ON CONFLICT (id) DO 
UPDATE SET
    owner_id = $2,
    name = $3,
    foundation_year = $4,
    phone_number = $5,
    opening_time = $6,
    closing_time = $7,
    working_days = $8,
    updated_at = NOW()
`

type SaveRestaurantParams struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Name           string
	FoundationYear sql.NullString
	PhoneNumber    sql.NullString
	OpeningTime    string
	ClosingTime    string
	WorkingDays    []string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

func (q *Queries) SaveRestaurant(ctx context.Context, arg SaveRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, saveRestaurant,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.FoundationYear,
		arg.PhoneNumber,
		arg.OpeningTime,
		arg.ClosingTime,
		pq.Array(arg.WorkingDays),
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
