name: Security Checks
on:
  push:
    branches:
      - master
      - dev
      - feature/*
      - hotfix/*
      - release/*
      - bugfix/*
      - integration/*
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  security_checks:
    uses: mechatron-x/go-workflows/.github/workflows/security_checks.yml@master
    with:
      go-version: ${{ vars.GO_VERSION }}
    secrets: inherit
